spring.application.name=TigerBoard

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/iste240?createDatabaseIfNotExist=true

# We use this hardcoded username and password as in ISTE 230 every student as the same username and password for their database.
# Change if you have changed your database username and password.
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.format_sql=true
